### ISSUE TITLE
images not synchronised

### ISSUE THREAD

**Issue by gitunit** [l0g1x/DUO-Camera-ROS#16] opened 2015-03-22 21:30 UTC
the images aren't synchronised! that's a big issue( i realised it the hard way, again ) you can record a rosbag file and watch it with rqt_bag.

the issue in my opinion is due to writing your own timestamp instead of using the device's timestamps.

**Comment by l0g1x** [comment] 2015-03-22 21:51
how would the using the device time stamp work? Im not sure if/how it gets the current time, but looking at other camera nodes that were written, i found that people where publishing the processed frame with the current time that the frame is being processed in. Right here im assigning the same time to both frames https://github.com/l0g1x/DUO-Camera-ROS/blob/indigo-devel/src/driverDUOstereo.cpp#L48 . How are you sure they are unsynchronized?

**Comment by l0g1x** [comment] 2015-03-22 21:55
maybe i should change it to this https://github.com/srv/camera1394stereo/blob/indigo/src/nodes/dev_camera1394stereo.cpp#L511 . I will also look into the time stamp that the DUO provides in the pFrameData pointer.

**Comment by gitunit** [comment] 2015-03-22 21:57
im quite sure the images with the current driver are not synchronised as i had problems showing the odometer using different implementations (viso2_ros, fovis_ros etc.) also looking inside a recorded bagfile it shows clearly that images are not in sync.
and yes, as you wrote right now, the best solution is using DUO's pFrameData->timeStamp. im going to try it out myself right now. :)

**Comment by gitunit** [comment] 2015-03-22 21:59
looking at your last link, that line
**ros::Time( double(frame->timestamp) \* 1.e-6 );**
this is a conversion to ros time, right?

**Comment by gitunit** [comment] 2015-03-22 22:18
DUO's time is 
**uint32_t timeStamp;             // DUO frame time stamp in 100us increments**

not sure if ros::Time is in same unit.

**Comment by l0g1x** [comment] 2015-03-22 23:00
http://docs.ros.org/api/rostime/html/time_8h_source.html#l00131 just need to make sure were using nsec. Looking at this now.

**Comment by gitunit** [comment] 2015-03-23 00:04
i tried some things, however without success so far. can you try to record a bagfile and look inside? i always get asynced images. when i look into other stereo bagfiles from the www they mostly are in sync.

**Comment by l0g1x** [comment] 2015-03-23 00:06
trying this now

**Comment by l0g1x** [comment] 2015-03-23 01:00
im running stereo_image_proc right now with your calibration files and its not complaining about the images being out of sync. i bagged left and right image raw data, and did `rostopic echo /duo3d_camera/left/image_raw | grep -C 3 stamp` on left and right and seems to me like sequences match up with time stamps:

left:

header: 
  seq: 137
  stamp: 
    secs: 1427071448
    nsecs: 365987476
  frame_id: duo3d_camera

header: 
  seq: 138
  stamp: 
    secs: 1427071448
    nsecs: 432443536
  frame_id: duo3d_camera

right:

header: 
  seq: 137
  stamp: 
    secs: 1427071448
    nsecs: 365987476
  frame_id: duo3d_camera

header: 
  seq: 138
  stamp: 
    secs: 1427071448
    nsecs: 432443536
  frame_id: duo3d_camera

**Comment by l0g1x** [comment] 2015-03-23 01:03
heres my bag: https://www.dropbox.com/s/7log56mx1rlb0zs/duosync.bag?dl=0

**Comment by gitunit** [comment] 2015-03-23 18:28
ok, i've looked into your bagfile and its the same result as i get. maybe its good enough (however not as good as in this [bagfile](https://docs.google.com/uc?export=download&confirm=ldd7&id=0B46akLGdg-uaOWtYT1ladldiS0U) ) and im wrong? still im not able to get any results with viso2_ros because it says that it doesn't get enough (0) synced images. have you ever tried to get an odometry with viso2_ros or fovis_ros ? i could get an odometry with the linked bagfile or other bagfiles from the viso2_ros site but not with the published images from the DUO.

**Comment by l0g1x** [comment] 2015-03-23 19:44
are you running the image_rect node inbetween?

**Comment by gitunit** [comment] 2015-03-23 19:55
yes i do. the following is what i use:

```
    <group ns="/duo3d_camera" if="$(arg viso2_odom)">

        <node pkg="stereo_image_proc" type="stereo_image_proc" name="stereo_image_proc">
            <param name="prefilter_size" type="int" value="5"/>
            <param name="prefilter_cap" type="int" value="5"/>
            <param name="correlation_window_size" type="int" value="5"/>
            <param name="min_disparity" type="int" value="-128"/>
            <param name="disparity_range" type="int" value="128"/>
            <param name="uniqueness_ratio" type="double" value="0.0"/>
            <param name="texture_threshold" type="int" value="100"/>
            <param name="speckle_size" type="int" value="0"/>
            <param name="speckle_range" type="int" value="31"/>
        </node>

    </group>

    <group if="$(arg viso2_odom)">          
        <node pkg="viso2_ros" type="stereo_odometer" name="stereo_odometer" output="screen">
            <remap from="stereo" to="duo3d_camera"/>
            <remap from="image" to="image_rect"/>
        </node>
    </group>
```

**Comment by gitunit** [comment] 2015-03-23 20:05
and this is how i use the TF publisher right after the DUO node:

```
        <arg name="pi/2" value="1.5707963267948966" />
        <arg name="camera" default="duo3d_camera" />
        <arg name="baseline/2" value="0.01505"/>
        <arg name="optical_translation" value="0 -$(arg baseline/2) 0"/>
        <arg name="optical_rotation" value="0 -$(arg pi/2) -$(arg pi/2)"/>

        <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_link"
            args="0 0 0.1 0 0 0 /base_link /$(arg camera) 100"/>  
        <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_optical_link"
            args="$(arg optical_translation) $(arg optical_rotation) /$(arg camera) /$(arg camera)_optical 100"/> 

```

**Comment by l0g1x** [comment] 2015-03-23 20:09
Can you give me a bag of _your_ data, not the viso2d one so i can try some things out in the mean time

**Comment by gitunit** [comment] 2015-03-23 20:19
ok, i will record something. only the images or do you want the TF also?

**Comment by gitunit** [comment] 2015-03-23 21:03
here you go, the [bagfile](https://drive.google.com/file/d/0B-EPlyC7czqdSUJ1aGZXSEo1Rzg/view?usp=sharing). TF topic included.

**Comment by l0g1x** [comment] 2015-03-23 22:02
Are you on hydro? Or did u install viso2 from source because theres no deb for indigo

Krystian Gebis
University of Illinois at Chicago

**Comment by gitunit** [comment] 2015-03-23 22:13
im on indigo and i installed viso2 from source.

**Comment by l0g1x** [comment] 2015-03-23 23:09
Is this the error you were getting? http://pastebin.com/kzScnbD1

**Comment by gitunit** [comment] 2015-03-23 23:13
yes. also i had another error where it sayed something about 0 synced images. i will try and post back.

**Comment by l0g1x** [comment] 2015-03-23 23:19
can you pastebin your full launch file

**Comment by gitunit** [comment] 2015-03-23 23:27
http://pastebin.com/yNdmXtWK

i run it with: **roslaunch duo3d_ros duo.launch viso2_odom:=true**

**Comment by l0g1x** [comment] 2015-03-23 23:56
if you set the debug level on viso2 to debug, you will see that the queue is of size zero and it is disregarding the messages coming in. Im not sure whether maybe im publishing the messages incorrectly, or you have viso2 setup wrong. I cant really do much more without being home and having the camera. Will look back into this in a couple of hours

**Comment by gitunit** [comment] 2015-03-24 00:06
thank you. maybe the TF is not published correctly? (i've never done this before, however i had someone look at it and he said, it looks ok - idk). the viso2 setup in the launchfile should be fine because its just the remapping of the camera and the image.

**Comment by l0g1x** [comment] 2015-03-24 00:11
can you do me a favor and try to use rtabmap_ros with live duo data? just add a publisher for base_link --> duo3d_camera tf. http://wiki.ros.org/rtabmap_ros/Tutorials/StereoOutdoorMapping Just get rid of the bag data stuff and rename the topics properly. Ive never used viso2 before, but i have used rtabmap ros and i know it works with the launch files they give you, just havent tried it yet with duo. i want to make sure something isnt wrong on my end and maybe its just a viso2 configuration issue

**Comment by gitunit** [comment] 2015-03-24 00:22
thats exactly why i tried viso2 in the first place because rtabmap_ros didn't work with DUO. Mathieu (from rtabmap) suggested i should try viso2 and fovis and see if i could get a simple odometry. ;)

**Comment by l0g1x** [comment] 2015-03-24 00:23
good to know.. thanks!

**Comment by gitunit** [comment] 2015-03-24 00:24
however, would you publish the base_link --> duo3d_camera differently to my setup in the launch file?

**Comment by l0g1x** [comment] 2015-03-24 00:27
it doesnt really matter, as long as your tf tree matches up when viso2 tries to do tf::lookupTransform. You will get a error if TF frames dont exist (like i did when i tried stripped down your launch file for simplicity, trying to eliminate if the tf setup was the issue, but didnt seem it was)

**Comment by gitunit** [comment] 2015-03-24 00:31
ok, thats good to know. i guess what matters regarding the TF frames is when you want a proper visualization in rviz, right?

**Comment by l0g1x** [comment] 2015-03-28 01:52
sorry for late response, out of town for past few days. To answer your question, yes. If you dont have a proper TF tree setup in rviz, or say your tree is disconnected somehow and you want to view your data in a global frame that is not connected with say the duo3d_camera frame, it will give you a error. Any update as to being able to use viso2? do you know if the issue is forsure on my side?

**Comment by gitunit** [comment] 2015-03-28 02:38
thx. i think its synced to some degree. i expected some perfect synced images like i've seen in some bagfiles but i guess the precision differs from camera to camera, doesn't it? however so far i didn't get any odometry with viso2 or rtabmap.

**Comment by l0g1x** [comment] 2015-03-28 03:06
https://github.com/l0g1x/DUO-Camera-ROS/blob/indigo-devel/src/driverDUOstereo.cpp#L49 
shows that the time stamps on both frames are the same. Stereo image proc works perfectly fine, and i know it would be the first one to complain if you didnt set the approximate_sync parameter, if the images where actually unsynced. I know this because of tinkering around and trying to use stereo image proc with two seperate usb cameras, also reading the docs for it

**Comment by l0g1x** [comment] 2015-03-28 03:07
Im going to close this issue for now, since it doesnt seem that this issue is coming from my side. Feel free to open it whenever if you find out that the issue is actually on my end.

**Closed as completed by l0g1x** 2015-03-28 03:07 UTC
Labels: bug
